name: libVILLAIN CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt-get install libglew-dev
        sudo apt-get install -y libsdl2-dev
        sudo apt-get install -y libsdl2-mixer-dev
        sudo apt-get install -y libsdl2-image-dev
        sudo apt-get install -y libsdl2-ttf-dev
        sudo apt-get install -y liblua5.4-dev
        sudo apt-get install -y libassimp-dev
    - name: configure engine
      run: ./configure.sh
    - name: build engine
      run: ./build.sh
    - name: build Sponza example
      run: |
        cd examples/3D
        ./configure.sh
        ./build.sh
    - name: build Zombie game
      run: |
        cd examples/ZombieGame
        ./configure.sh
        ./build.sh
    - name: build Bullet Physics Demo
      run: |
        cd examples/Bullet
        ./configure.sh
        ./build.sh
    - name: build Box2D Demo
      run: |
        cd examples/Platformer
        ./configure.sh
        ./build.sh

    - name: build FPS Game
      run: |
        cd examples/FPS
        ./configure.sh
        ./build.sh
