name: libVILLAIN CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache dependencies
      uses: actions/cache@v1.2.1
      with:
        path: |
          /usr/include
          /usr/lib/x86_64-linux-gnu
        key: ${{ runner.os }}-cpp-deps-${{ hashFiles('apt-packages.txt') }}
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libglew-dev \
          libsdl2-dev \
          libopenal-dev \
          liblua5.4-dev \
          libassimp-dev \
          lcov \
          cppcheck
    - name: Perform static analysis
      run: cppcheck --error-exitcode=1 src/
    - name: Run unit tests
      run: |
        ./configure.sh
        ./build.sh
        ./runTests.sh
    - name: Build Sponza example
      run: |
        cd examples/3D
        ./configure.sh
        ./build.sh
    - name: Build Zombie game
      run: |
        cd examples/ZombieGame
        ./configure.sh
        ./build.sh
    - name: Build Box2D Demo
      run: |
        cd examples/Platformer
        ./configure.sh
        ./build.sh
